from dataclasses import dataclass
from pathlib import Path
from agent.registry import register_agent

@dataclass
class AgentSpec:
    name: str
    description: str
    goal: str


def generate_agent(spec: AgentSpec):
    base_path = Path("generated") / spec.name
    agent_path = base_path / "agent"

    agent_path.mkdir(parents=True, exist_ok=True)

    (agent_path / "main.py").write_text(
        f'''def main():
    print("Agent: {spec.name}")
    print("Goal: {spec.goal}")
    print("Status: running")

if __name__ == "__main__":
    main()
'''
    )

    (base_path / "README.md").write_text(
        f"""# {spec.name}

## Description
{spec.description}

## Goal
{spec.goal}

## Status
Autogenerated by Agent Factory.
"""
    )

    print(f"[Factory] Child agent generated at: {base_path}")


def register_child_agent(spec: AgentSpec):
    result = register_agent(spec.name)

    agent_id = result["agent"]["id"]

    print(f"[Factory] Registered child agent: {spec.name}")
    print(f"[Factory] child agentId: {agent_id}")

    return {
        "agentId": agent_id,
        "name": spec.name
    }
