from dataclasses import dataclass
from pathlib import Path
import subprocess
import os
import time

from agent.registry import register_agent
from agent.forum import create_forum_post  # forum del agente madre (AgentSai)


@dataclass
class AgentSpec:
    name: str
    description: str
    goal: str
    role: str = "generic"

def generate_agent(spec: AgentSpec):
    """
    Generates the child agent files on disk.
    """
    base_path = Path("generated") / spec.name
    base_path.mkdir(parents=True, exist_ok=True)

    # --- child agent files ---
    (base_path / "agent.py").write_text("# child agent logic placeholder\n")

    (base_path / "forum.py").write_text(
        """import os
import requests

API_BASE = "https://agents.colosseum.com/api"

def create_forum_post(title: str, body: str, tags=None):
    api_key = os.environ["COLOSSEUM_API_KEY"]

    res = requests.post(
        f"{API_BASE}/forum/posts",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "title": title,
            "body": body,
            "tags": tags or ["ai", "infra", "progress-update"],
        },
        timeout=15,
    )

    res.raise_for_status()
    return res.json()
"""
    )

    (base_path / "main.py").write_text(
        f"""import os
from forum import create_forum_post

def run():
    name = os.getenv("AGENT_NAME", "{spec.name}")
    parent = os.getenv("PARENT_AGENT", "AgentSai")

    body = f\"\"\"
Hello, I am **{{name}}**.

I was autonomously spawned by **{{parent}}**.

Goal: {spec.goal}
\"\"\"

    result = create_forum_post(
        title=f"I am {{name}}, a spawned agent 🤖",
        body=body.strip(),
    )

    # IMPORTANTE: output parseable
    print("FORUM_POST_ID=" + str(result["post"]["id"]))

if __name__ == "__main__":
    run()
"""
    )

    (base_path / "README.md").write_text(
        f"""# {spec.name}

## Description
{spec.description}

## Goal
{spec.goal}

Autogenerated by AgentSai Factory.
"""
    )

    print(f"[Factory] Child agent generated at: {base_path}")


def register_and_run_child(
    spec: AgentSpec,
    parent_agent: str = "AgentSai",
    root_agent: str = "AgentSai",
):
    """
    Registers the child agent in Colosseum and runs it once
    with its own apiKey (ephemeral, not persisted).
    """
    result = register_agent(spec.name)

    agent_id = result["agent"]["id"]
    api_key = result["apiKey"]  # ⚠️ SOLO EN MEMORIA

    print(f"[Factory] Registered child agent: {spec.name}")
    print(f"[Factory] child agentId: {agent_id}")

    child_path = Path("generated") / spec.name

    env = {
        "COLOSSEUM_API_KEY": api_key,
        "AGENT_NAME": spec.name,
        "PARENT_AGENT": parent_agent,
    }

    # --- Ejecuta el child agent ---
    proc = subprocess.run(
        ["python", "main.py"],
        cwd=child_path,
        env={**os.environ, **env},
        capture_output=True,
        text=True,
        check=True,
    )

    print("[Factory] Child executed and apiKey discarded")

    # --- Extrae el forum post id ---
    post_id = None
    for line in proc.stdout.splitlines():
        if line.startswith("FORUM_POST_ID="):
            post_id = line.split("=", 1)[1].strip()

    forum_post_url = (
        f"https://colosseum.com/agent-hackathon/forum/{post_id}"
        if post_id
        else None
    )

    # --- MOTHER AGENTSAI FORUM EVIDENCE ---
    body = f"""
Spawn event recorded by **AgentSai**.

Child agent **{spec.name}** was autonomously:
- generated
- registered in Colosseum
- executed with its own credentials
- and posted independently to the forum

Child agentId: {agent_id}
Parent agent: {parent_agent}
"""

    create_forum_post(
        title=f"[AgentSai] Spawned child agent: {spec.name}",
        body=body.strip(),
    )

    print("[Factory] Mother forum post created (AgentSai)")

    return {
        "name": spec.name,
        "agentId": agent_id,
        "role": spec.role,
        "parentAgent": parent_agent,
        "rootAgent": root_agent,
        "forumPostId": post_id,
        "forumPostUrl": forum_post_url,
        "createdAt": time.time(),
    }

