from dataclasses import dataclass
from pathlib import Path

@dataclass
class AgentSpec:
    name: str
    description: str
    goal: str


def generate_agent(spec: AgentSpec):
    """
    Generates a minimal autonomous agent based on a spec.
    Deterministic, no prompts, no LLM yet.
    """

    base_path = Path("generated") / spec.name
    agent_path = base_path / "agent"

    agent_path.mkdir(parents=True, exist_ok=True)

    # --- generated/<agent>/agent/main.py ---
    (agent_path / "main.py").write_text(
        f'''def main():
    print("Agent: {spec.name}")
    print("Goal: {spec.goal}")
    print("Status: running")

if __name__ == "__main__":
    main()
'''
    )

    # --- generated/<agent>/README.md ---
    (base_path / "README.md").write_text(
        f"""# {spec.name}

## Description
{spec.description}

## Goal
{spec.goal}

## Status
Autogenerated by Agent Factory.
"""
    )

    print(f"[Factory] Child agent generated at: {base_path}")
